package FactoryDesignPattern.Factories;

import FactoryDesignPattern.Products.ProductInterface;

// ALWAYS REMEMBER THIS CREATOR INTERFACE WILL ALWAYS
// HAVE A CREATE PRODUCT METHOD IN THE INTERFACE AND
// FOR EVERY DIFFERENT PRODUCT WE WILL HAVE DIFFERENT CREATOR IMPL CLASS WHICH WILL BE RETURING
// THE DIFFERENT INSATANCES WITH THE DIFFERENT IMPLEMENTATION CLASS
public interface CreatorInterface {
    ProductInterface createProduct();
}
